// generated by stringer -type=EventType; DO NOT EDIT

package event

import "fmt"

const _EventType_name = "BUTTON_EVENTCHARACTER_EVENTSLIDER_EVENTAXIS_EVENTPOINTER_ACTIVATIONPOINTER_DEACTIVATION"

var _EventType_index = [...]uint8{0, 12, 27, 39, 49, 67, 87}

func (i EventType) String() string {
	if i+1 >= EventType(len(_EventType_index)) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
